### PR TITLE
Add dependency to psycopg-binary

### LINKED ISSUE #880: Missing psycopg 'binary' implementation extra since 0.30.0?
```
Traceback (most recent call last):
<trimmed>
2023-12-27T14:52:56.489748780Z     import procrastinate
2023-12-27T14:52:56.489765680Z   File "/code/.venv/lib/python3.11/site-packages/procrastinate/__init__.py", line 8, in <module>
2023-12-27T14:52:56.489772822Z     from procrastinate.psycopg_connector import PsycopgConnector
2023-12-27T14:52:56.489825630Z   File "/code/.venv/lib/python3.11/site-packages/procrastinate/psycopg_connector.py", line 6, in <module>
2023-12-27T14:52:56.489846036Z     import psycopg
2023-12-27T14:52:56.489930920Z   File "/code/.venv/lib/python3.11/site-packages/psycopg/__init__.py", line 9, in <module>
2023-12-27T14:52:56.490090247Z     from . import pq  # noqa: F401 import early to stabilize side effects
2023-12-27T14:52:56.490108558Z     ^^^^^^^^^^^^^^^^
2023-12-27T14:52:56.490116210Z   File "/code/.venv/lib/python3.11/site-packages/psycopg/pq/__init__.py", line 114, in <module>
2023-12-27T14:52:56.490339001Z     import_from_libpq()
2023-12-27T14:52:56.490353415Z   File "/code/.venv/lib/python3.11/site-packages/psycopg/pq/__init__.py", line 106, in import_from_libpq
2023-12-27T14:52:56.490515846Z     raise ImportError(
2023-12-27T14:52:56.490529522Z ImportError: no pq wrapper available.
2023-12-27T14:52:56.490535698Z Attempts made:
2023-12-27T14:52:56.490541408Z - couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
2023-12-27T14:52:56.490547388Z - couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
2023-12-27T14:52:56.490553206Z - couldn't import psycopg 'python' implementation: libpq library not found
```

Looking at #863, `psycopg = {extras = ["pool"], version = "^3.1.13"}` was added but without the `"binary"` extra package. This causes an import error for existing users who don't currently declare the depdendency directly.

Easily worked around but probably a question for @aleksandr-shtaub as to whether the omission was deliberate (i.e. to allow users of procrastinate which of the 3 implementations they use) or should we add the dependency explicitly (which would be consistent as `"psycopg2-binary"` is alreay there).

### PR DESCRIPTION
**Pull request by ewjoachim**
Closes #880 

@ashleyheath would you mind trying out this PR and letting me know if it works in your case ?

### Successful PR Checklist:

- [ ] Tests
  - [x] (not applicable?)
- [ ] Documentation
  - [x] (not applicable?)

### CODE REVIEW

**Comment by ashleyheath** [comment]
@ewjoachim, have spent a while today trying to apply these into a reproducable project but haven't made great progress. Am afraid I probably won't get any more time to look at it this week but the code changes in the PR look good to me regardless so am happy for you to merge them in as-is if you're happy with them (and if so, I can quickly pick up the new release and verify that in our build). Otherwise I can try pick this up again next week.

**Comment by ewjoachim** [comment]
Sorry for the time lost. Let's merge.

**Comment by ashleyheath** [comment]
Have pulled the new release into our build pipeline and can confirm it fixes the original issue.

**Comment by ewjoachim** [comment]
Perfect!

I'm delighted that you're taking interest into contributing to the project. As you probably saw in other PRs, I'm partly in the middle of redoing some parts (especially around the sync/async situation which is currently subpar).

Would you like to be part of the effort of trying out the pre-release when this comes out?

It might include switching to Psycopg3. It looks like I'll never be able to provide a good UX with psycopg2 nor aiopg, but I'm still wondering if I should leave the psycopg2 and aiopg connectors around with a disclaimer that they'll likely cause issues for non-purely async projects, or remove it and make it harder for existing users, but better in the long run)

**Comment by turicas** [comment]
@ewjoachim how do you plan to support Django when moving to psycopg3? As far as I know, only [Django 4.2+ supports psycopg3 DB backend](https://django.readthedocs.io/en/latest/releases/4.2.html#psycopg-3-support) and it could be difficult to deal with Django using psycopg2 and procrastinate using psycopg3 in the same project (there are a lot of software out there using an earlier version of Django).

**Comment by ewjoachim** [comment]
@turicas

**Comment by ashleyheath** [comment]
> Would you like to be part of the effort of trying out the pre-release when this comes out?

Yep; very happy to! Will pick up on the discussion thread if/when I have comments to add

**Pull request merged**
