### PR TITLE
Fix parsing of defer CLI command --at and --in options

### LINKED ISSUE #997: CLI: procrastinate defer --at and --in not recognized
## System info
`procrastinate` version: Both 1.1.2 and 2.0.0

## Problem
I've been following the tutorial in docs, and bumped into an error in CLI.

```sh
procrastinate defer --at=2024-03-18T18:42:00+01:00 sum '{"a": 7, "b": 5}'
```

This fails with following output:

```
Task.configure() got an unexpected keyword argument 'at'
```

The same is true when using `--in` argument.

## Context

I suspect this is caused by recent rewrite of CLI module to be fully asynchronous (getting rid of `click`).

If you're interested in a PR, I'd probably be able to find the right call and fix this.

### PR DESCRIPTION
**Pull request by stinovlas**
Closes #997 

I fixed parsing of `--at` and `--in` CLI options of `defer` command and added two integration tests for those.

### Successful PR Checklist:

- [x] Tests
  - yes, I added two integration tests covering defer --at and --in options
- [x] Documentation not applicable – just a bugfix

#### PR label(s): 
  - [x] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20bugfix%20%F0%9F%95%B5%EF%B8%8F

### CODE REVIEW

**Review by ewjoachim — APPROVED** [review]
Congratulations for your first contribution, welcome to the joyful bunch of procrastinators :)

**Comment by stinovlas** [comment]
> Congratulations for your first contribution, welcome to the joyful bunch of procrastinators :)

Thanks :⁠-⁠). There are still some tests failing in the CI, I'll fix that tomorrow.

**Comment by stinovlas** [comment]
> > Congratulations for your first contribution, welcome to the joyful bunch of procrastinators :)
> 
> Thanks :⁠-⁠). There are still some tests failing in the CI, I'll fix that tomorrow.

Fixed! (I hope, `pytest` passes on my machine now, but PR CI requires approval)

**Comment by ewjoachim** [comment]
Seems all good. Don't forget to squash your fixups :)

**Comment by stinovlas** [comment]
> Seems all good. Don't forget to squash your fixups :)

Sure, I wasn't sure what's the convention here (whether you squash it during merge or if it's the PR author responsibility). Squashed :-).

**Comment by ewjoachim** [comment]
> I wasn't sure what's the convention here

It depends. When contributors put some effort on commit names, I try to keep it in the history. When the commit log looks like this, I squash.


[image](https://xkcd.com/1296/)

**Comment by stinovlas** [comment]
> > I wasn't sure what's the convention here
> 
> It depends. When contributors put some effort on commit names, I try to keep it in the history. When the commit log looks like this, I squash.

Makes sense :-).

This is weird. All I did was squash the fixup with the previous commit, which produced the exactly same code, but now the CI is failing in a part of the code that shouldn't have anything in common with the changes. And it passed in py3.8 and py3.10, but failed in py3.11. It seems to be some kind of race-condition random error? It doesn't pass for me on `main` either. But I'm not yet familiar with the `procrastinate` codebase enough to be sure.

**Comment by ewjoachim** [comment]
Yup, seems like a test decided to become flaky all of a sudden. I've rerun the CI, if there's a fix to do, we'll do it in another PR.

**Pull request merged**
