### PR TITLE
Use typing_extensions only if Python < 3.8

### LINKED ISSUE #644: Missing `typing_extensions` from dependencies
Hey - new here so forgive me if I'm missing something obvious.

I was testing Procrastinate for use on a project, and I ran into a dependency that might need to be added to your pyproject.toml. I haven't used Poetry before so don't know how that works exactly... I've only ever used requirements.txt.

I'm running python 3.9. I got a dependency error when I tried running the package. It said I needed to install **typing_extensions**.

Maybe that's just a basic package that should already be installed by default, idk - but if not, there you go, a quick add to your list so users can install more quickly.

### PR DESCRIPTION
**Pull request by pmav99**
Closes #644

### Successful PR Checklist:

- [ ] Tests
  - [x] (not applicable?)
- [ ] Documentation
  - [x] (not applicable?)

### CODE REVIEW

**Comment by pmav99** [comment]
The failures don't seem to be related to the changes.

**Comment by ewjoachim** [comment]
Yes, the same error suddenly appeared in an unrelated PR: https://github.com/procrastinate-org/procrastinate/pull/655

I'll fix it on a different PR, don't mind that :)

**Comment by ewjoachim** [comment]
BTW, glad to see you've made it to your first public PR ! Congratulations :) And it's nice too !

**Comment by ewjoachim** [comment]
Ok, I've fixed the problem (it was actually due to the update of deps in this PR, but it was due to some of the deps that got upgraded along the way, so nothing bad on your side).

I've rebased your PR and reran `poetry update`.

We should be able to merge as soon as CI passes.

**Review by ewjoachim — APPROVED** [review]

**Pull request merged**
