### PR TITLE
Fix SchemaManager.apply_schema

### LINKED ISSUE #1115: Apply migrations using plain python
Im trying to run migrations without using the CLI options.

I currently have this little piece of code:

```python
from procrastinate import App, PsycopgConnector


app = App(
    connector=PsycopgConnector(
        kwargs={
            "host": "localhost",
            "user": "postgres",
            "password": "password",
            "port": "5432"
        }
    )
)


with app.open():
    app.schema_manager.apply_schema()
```

But the error is quite confusing as I'm already using the context manager:

```
raise exceptions.AppNotOpen
procrastinate.exceptions.AppNotOpen: 
    App was not open. Procrastinate App needs to be opened using:

    - ``app.open()``,
    - ``await app.open_async()``,
    - ``with app.open():``,
    - ``async with app.open_async():``.
```

Can anyone please give me a hint?

### PR DESCRIPTION
**Pull request by ewjoachim**
Closes #1115 

I'm trying to think about a test that would make sense to catch the issue, and thinking of none. Any idea ? (@onlyann @medihack ?)

### Successful PR Checklist:

- [ ] Tests
  - [ ] (not applicable?)
- [ ] Documentation
  - [x] (not applicable?)

#### PR label(s): 
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20breaking%20%F0%9F%92%A5
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20feature%20%E2%AD%90%EF%B8%8F
  - [x] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20bugfix%20%F0%9F%95%B5%EF%B8%8F
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20miscellaneous%20%F0%9F%91%BE
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20dependencies%20%F0%9F%A4%96
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20documentation%20%F0%9F%93%9A

### CODE REVIEW

**Comment by medihack** [comment]
I probably don't quite understand it, but why not just do an integration test that looks similar to the original code in the issue and then check if the schema was created in the database or if no error was raised?

**Comment by ewjoachim** [comment]
I was thinking the amount of code needed to get a DB that's not already migrated might be annoying, but actually, it might be ok.

**Comment by onlyann** [comment]
That or a unit test that asserts the correct connector is being called in this scenario.

If the integration test is simple enough, even better I guess.

**Comment by ewjoachim** [comment]
Added a test that reproduced the issue.

**Review by onlyann — APPROVED** [review]

**Pull request merged**
