### PR TITLE
Run sync task in its own thread

### LINKED ISSUE #1124: Creating an asyncio loop in a sync task
> One of my colleagues had a [...] problem. He didn't know that the worker runs under asyncio and used `asyncio.run` in a synchronous task to create a new event loop, leading to a similar error.
The worker is [calling `sync_to_async`](https://github.com/procrastinate-org/procrastinate/blob/e94b4d0427b75a479f20ceed57a93cb5477c831c/procrastinate/worker.py#L278) with the default `thread_sensitive` set to `True`. I made a quick and dirty attempt, set `thread_sensitive` to `False`, and our error was gone (in the end, we rewrote the code of the task to be async). I wonder what the (negative) implications would be if we change the worker code to use `thread_sensitive=False`.

_Originally posted by @medihack in https://github.com/procrastinate-org/procrastinate/issues/609#issuecomment-2245449737_

### PR DESCRIPTION
**Pull request by medihack**
Closes #1124

### Successful PR Checklist:

- [x] Tests
  - [ ] (not applicable?)
- [ ] Documentation
  - [ ] (not applicable?)

#### PR label(s): 
  - [x] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20breaking%20%F0%9F%92%A5
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20feature%20%E2%AD%90%EF%B8%8F
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20bugfix%20%F0%9F%95%B5%EF%B8%8F
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20miscellaneous%20%F0%9F%91%BE
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20dependencies%20%F0%9F%A4%96
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20documentation%20%F0%9F%93%9A

### CODE REVIEW

**Comment by medihack** [comment]
Running the sync task in its own thread ensures that it is more isolated. The test looks a bit constructed but fails (even without any exception) when the sync task runs in the main thread (`thread_sensitive=True`).
I tried to find any negative consequences (especially for Django), but as db connections in Django are created per thread, I don't see any. However, I am not absolutely sure.

**Comment by ewjoachim** [comment]
The discussions in Discord are prompting me to wonder: if we're considering changing this, should we consider running sync tasks in subprocesses ? It would avoid threading issues and would make it much easier to kill a task or to send a signal, the same way we do with async. But I don't want this decision to be made lightly and later regretted.

**Comment by medihack** [comment]
When doing IO-heavy stuff, an async task is preferred over a threaded sync task. (If the task depends on a non-async third-party library, then the chances are high that there is an async alternative.) On the other hand, if the task is compute-heavy, then running it in its own process is the way to go.

As mentioned, we also could make this configurable. As an option for the worker, for example as [huey does it](https://huey.readthedocs.io/en/latest/consumer.html#worker-types) (but they chose threaded as the default), or as an option on the task itself (something like `@app.task(sync_threaded=True`). But even then, the question remains what the default should be (in my opinion, for the above-mentioned reason, a separate process).

**Comment by ewjoachim** [comment]
If we did:
`async def` -> async (good for I/O & high level of parallelism, bad for CPU)
`def` -> subprocess (low level of parallelism, not specifically bad for I/O, good for CPU)

That would be not that far from what we have today, would it ?

**Comment by onlyann** [comment]
It sounds reasonable to remove the thread sensitivity when wrapping sync tasks into a Thread.

Maybe this change could be merged while the conversation of introducing sub-processes for CPU bound tasks carries on?

**Comment by medihack** [comment]
> If we did:
> `async def` -> async (good for I/O & high level of parallelism, bad for CPU)
> `def` -> subprocess (low level of parallelism, not specifically bad for I/O, good for CPU)

Yes, this is what I had in mind (when not making it configurable). We would then run the sync task in a `ProcessPoolExecutor`. I also looked a bit around how other distributed (Python) task queues handle this:

- Celery -> [process](https://docs.celeryq.dev/en/stable/userguide/workers.html#concurrency)
- RQ -> [process](https://python-rq.org/docs/workers/)
- Huey -> [thread by default, but separate process optional](https://huey.readthedocs.io/en/latest/consumer.html#worker-types)
- Django-q2 -> [process, but using a worker pool](https://django-q2.readthedocs.io/en/master/cluster.html)
- django-task -> [inside same thread and process](https://github.com/RealOrangeOne/django-tasks/blob/00a9bf6a0cbd21d537305a687be0a2d484ba341d/django_tasks/backends/database/management/commands/db_worker.py#L129)

So, the majority seem to use a separate process.

As you already mentioned, another advantage of using a separate process is that it can be killed. That way, we could even introduce some final shutdown timeout that forces the worker to be entirely stopped (see discussion on Discord). I don't know if this is even possible when only using threads. Another feature that would be possible by using a separate process for a sync task is to specify the maximum time a task can take.

> Maybe this change could be merged while the conversation of introducing sub-processes for CPU bound tasks carries on?

Either way, we said it is a breaking change (is it?!) targeted at v3. So, it won't be in a near-term 2.x release. Or should we merge this one into the main branch and work on a "sub-process" variant in the v3 branch?

**Comment by onlyann** [comment]
> Either way, we said it is a breaking change (is it?!) targeted at v3. So, it won't be in a near-term 2.x release. Or should we merge this one into the main branch and work on a "sub-process" variant in the v3 branch?

A merge into `main` is fine if someone needs it prior to v3 release.
It could be argued it is not a breaking given there is no mention in the docs that sync tasks block each other, and I can hardly imagine a use of this library using long running sync tasks because of it.

That said, my comment was just about merging it into `v3`. Maybe it won't ever make it to the release if everything is a sub-process but we are better off iterating without thread sensitivity until then.

**Comment by medihack** [comment]
> A merge into `main` is fine if someone needs it prior to v3 release. It could be argued it is not a breaking change given there is no mention in the docs that sync tasks block each other, and I can hardly imagine a use of this library using long running sync tasks because of it.

Yes, I think so, too. One can even argue that the current implementation is even a bug as concurrent sync tasks are never processed in parallel (but consecutively in the main thread).
@ewjoachim Would it be ok if we merge this into the main branch, make a minor release, and open another issue / PR with a subprocess implementation?

**Comment by medihack** [comment]
> Yep. Will try to review asap !

Sure, no hurry. Just wanted to know if it's ok when I switch the target branch. I will change it to main.

**Pull request closed without merging**
