### PR TITLE
Merge main into v3

### PR DESCRIPTION
**Pull request by medihack**
Pull main into v3, solve conflicts. Also, updated dependencies.

### Successful PR Checklist:

- [ ] Tests
  - [x] (not applicable?)
- [ ] Documentation
  - [x] (not applicable?)

#### PR label(s): 
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20breaking%20%F0%9F%92%A5
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20feature%20%E2%AD%90%EF%B8%8F
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20bugfix%20%F0%9F%95%B5%EF%B8%8F
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20miscellaneous%20%F0%9F%91%BE
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20dependencies%20%F0%9F%A4%96
  - [ ] https://github.com/procrastinate-org/procrastinate/labels/PR%20type%3A%20documentation%20%F0%9F%93%9A

### CODE REVIEW

**Comment by ewjoachim** [comment]
Were there still conflicts after my last pass ? Nothing too complex I hope ?

**Review by ewjoachim — APPROVED** [review]

**Comment by medihack** [comment]
> Were there still conflicts after my last pass ? Nothing too complex I hope ?

Nope, minor. I struggled more with the .pre-commit-config.yml constantly got overridden (for one hour or so 😂). But then, at some point, I realized how poetry-to-pre-commit works 😉.

**Comment by ewjoachim** [comment]
Oh wow, sorry for the time loss ! Do you think we should write about that in CONTRIBUTING.md ?

**Comment by medihack** [comment]
> Oh wow, sorry for the time loss ! Do you think we should write about that in CONTRIBUTING.md ?

It's not too bad. As a result, I learned a bit about pre-commit, which also benefits my other projects. I can add a little hint to the docs, on the other hand we can't document everything.

**Pull request merged**
